<?php
include "conexao.php";

if(isset($_GET['us'])){
$us=$_GET['us'];	
	}

	$us=base64_decode($us);
	$sql="select * from tbl_usuario where `PK_Login`='$us'";
	$comando=mysql_query($sql);
	$linhap=mysql_fetch_array($comando);
	$medio=$linhap['Nivel_Acesso'];
	$usu=$linhap['FK_Etec'];
	$us=base64_encode($us);


		mysql_query("SET NAMES 'latin1'");
        mysql_query('SET character_set_connection=latin1');
        mysql_query('SET character_set_client=latin1');
        mysql_query('SET character_set_results=latin1');
// Definimos o nome do arquivo que será exportado
$arquivo = 'lista_espacofisico.xls';
if($medio=="Administrador"){
   $query = "select * from tbl_espaco_fisico inner join tbl_etec on tbl_espaco_fisico.FK_Instituicao=tbl_etec.PK_CodEtec inner join tbl_cadastrolaboratorio on tbl_cadastrolaboratorio.PK_CodLaboratorio=tbl_espaco_fisico.FK_Laboratorio";
   }else{
	$query = "select * from tbl_espaco_fisico inner join tbl_etec on tbl_espaco_fisico.FK_Instituicao=tbl_etec.PK_CodEtec inner join tbl_cadastrolaboratorio on tbl_cadastrolaboratorio.PK_CodLaboratorio=tbl_espaco_fisico.FK_Laboratorio where tbl_espaco_fisico.FK_Instituicao=$usu"; 
   }
$resultado = mysql_query ($query);

$html = '';
$html .= '<table border=1>';
$html .= '<tr>';
$html .= '<td colspan=5 align=center><b>Equipamentos</b></tr>';
$html .= '</tr>';
$html .= '<tr>';
$html .= '<td><b>Instituição</b></td>';
$html .= '<td><b>Laboratório</b></td>';
$html .= '<td><b>Descrição Laboratório</b></td>';
$html .= '<td><b>Capacidade</b></td>';
$html .= '<td><b>Area</b></td>';
$html .= '<td><b>Tipo de Construção</b></td>';
$html .= '<td><b>Quantidade de Curso</b></td>';
$html .= '<td><b>Ociosidade</b></td>';
$html .= '<td><b>Quantidade de Bancadas</b></td>';
$html .= '<td><b>Mseg</b></td>';
$html .= '<td><b>Mter</b></td>';
$html .= '<td><b>Mqua</b></td>';
$html .= '<td><b>Mqui</b></td>';
$html .= '<td><b>Msex</b></td>';
$html .= '<td><b>Msab</b></td>';
$html .= '<td><b>Tseg</b></td>';
$html .= '<td><b>Tter</b></td>';
$html .= '<td><b>Tqua</b></td>';
$html .= '<td><b>Tqui</b></td>';
$html .= '<td><b>Tsex</b></td>';
$html .= '<td><b>Tsab</b></td>';
$html .= '<td><b>Nseg</b></td>';
$html .= '<td><b>Nter</b></td>';
$html .= '<td><b>Nqua</b></td>';
$html .= '<td><b>Nqui</b></td>';
$html .= '<td><b>Nsex</b></td>';
$html .= '<td><b>Nsab</b></td>';
$html .= '<td><b>Seg10</b></td>';
$html .= '<td><b>Seg11</b></td>';
$html .= '<td><b>Seg12</b></td>';
$html .= '<td><b>Seg13</b></td>';
$html .= '<td><b>Seg14</b></td>';
$html .= '<td><b>Seg15</b></td>';
$html .= '<td><b>Seg16</b></td>';
$html .= '<td><b>Seg17</b></td>';
$html .= '<td><b>Seg18</b></td>';
$html .= '<td><b>Seg19</b></td>';
$html .= '<td><b>Seg20</b></td>';
$html .= '<td><b>Seg21</b></td>';
$html .= '<td><b>Seg22</b></td>';
$html .= '<td><b>Ter10</b></td>';
$html .= '<td><b>Ter11</b></td>';
$html .= '<td><b>Ter12</b></td>';
$html .= '<td><b>Ter13</b></td>';
$html .= '<td><b>Ter14</b></td>';
$html .= '<td><b>Ter15</b></td>';
$html .= '<td><b>Ter16</b></td>';
$html .= '<td><b>Ter17</b></td>';
$html .= '<td><b>Ter18</b></td>';
$html .= '<td><b>Ter19</b></td>';
$html .= '<td><b>Ter20</b></td>';
$html .= '<td><b>Ter21</b></td>';
$html .= '<td><b>Ter22</b></td>';
$html .= '<td><b>Quar10</b></td>';
$html .= '<td><b>Quar11</b></td>';
$html .= '<td><b>Quar12</b></td>';
$html .= '<td><b>Quar13</b></td>';
$html .= '<td><b>Quar14</b></td>';
$html .= '<td><b>Quar15</b></td>';
$html .= '<td><b>Quar16</b></td>';
$html .= '<td><b>Quar17</b></td>';
$html .= '<td><b>Quar18</b></td>';
$html .= '<td><b>Quar19</b></td>';
$html .= '<td><b>Quar20</b></td>';
$html .= '<td><b>Quar21</b></td>';
$html .= '<td><b>Quar22</b></td>';
$html .= '<td><b>Quin10</b></td>';
$html .= '<td><b>Quin11</b></td>';
$html .= '<td><b>Quin12</b></td>';
$html .= '<td><b>Quin13</b></td>';
$html .= '<td><b>Quin14</b></td>';
$html .= '<td><b>Quin15</b></td>';
$html .= '<td><b>Quin16</b></td>';
$html .= '<td><b>Quin17</b></td>';
$html .= '<td><b>Quin18</b></td>';
$html .= '<td><b>Quin19</b></td>';
$html .= '<td><b>Quin20</b></td>';
$html .= '<td><b>Quin21</b></td>';
$html .= '<td><b>Quin22</b></td>';
$html .= '<td><b>Sex10</b></td>';
$html .= '<td><b>Sex11</b></td>';
$html .= '<td><b>Sex12</b></td>';
$html .= '<td><b>Sex13</b></td>';
$html .= '<td><b>Sex14</b></td>';
$html .= '<td><b>Sex15</b></td>';
$html .= '<td><b>Sex16</b></td>';
$html .= '<td><b>Sex17</b></td>';
$html .= '<td><b>Sex18</b></td>';
$html .= '<td><b>Sex19</b></td>';
$html .= '<td><b>Sex20</b></td>';
$html .= '<td><b>Sex21</b></td>';
$html .= '<td><b>Sex22</b></td>';
$html .= '<td><b>Sab10</b></td>';
$html .= '<td><b>Sab11</b></td>';
$html .= '<td><b>Sab12</b></td>';
$html .= '<td><b>Sab13</b></td>';
$html .= '<td><b>Sab14</b></td>';
$html .= '<td><b>Sab15</b></td>';
$html .= '<td><b>Sab16</b></td>';
$html .= '<td><b>Sab17</b></td>';
$html .= '<td><b>Sab18</b></td>';
$html .= '<td><b>Sab19</b></td>';
$html .= '<td><b>Sab20</b></td>';
$html .= '<td><b>Sab21</b></td>';
$html .= '<td><b>Sab22</b></td>';
$html .= '<td><b>Obs_Geral</b></td>';
$html .= '<td><b>AmbienteDescricao</b></td>';
$html .= '<td><b>Quadro de Energia</b></td>';
$html .= '<td><b>Tomada110v</b></td>';
$html .= '<td><b>Tomada220v</b></td>';
$html .= '<td><b>Tomada200v</b></td>';
$html .= '<td><b>Tipo_Iluminacao</b></td>';
$html .= '<td><b>Quantidade_Luminarias</b></td>';
$html .= '<td><b>Pe_Direito</b></td>';
$html .= '<td><b>Tipo_Revestimento</b></td>';
$html .= '<td><b>Quantidade_Portas</b></td>';
$html .= '<td><b>Medida_PortaLargura</b></td>';
$html .= '<td><b>Medida_PortaAltura</b></td>';
$html .= '<td><b>Equipamento_Seguranca</b></td>';
$html .= '<td><b>Exaustor</b></td>';
$html .= '<td><b>Curso</b></td>';
$html .= '</tr>';

while($linha = mysql_fetch_array ($resultado)){



$html .= '<tr>';
$html .= '<td>' .$linha['Etec']. '</td>';
$html .= '<td>' . $linha['Nome_Laboratorio']. '</td>';
$html .= '<td>' . $linha['Descricao']. '</td>';
$html .= '<td>' . $linha['Capacidade']. '</td>';
$html .= '<td>' . $linha['Area']. '</td>';
$html .= '<td>' . $linha['tipo_construcao']. '</td>';
$html .= '<td>' . $linha['quantidade_curso']. '</td>';
$html .= '<td>' . $linha['Ociosidade']. '</td>';
$html .= '<td>' . $linha['Quantidade_Bancadas']. '</td>';
$html .= '<td>' . $linha['Mseg']. '</td>';
$html .= '<td>' . $linha['Mter']. '</td>';
$html .= '<td>' . $linha['Mqua']. '</td>';
$html .= '<td>' . $linha['Mqui']. '</td>';
$html .= '<td>' . $linha['Msex']. '</td>';
$html .= '<td>' . $linha['Msab']. '</td>';
$html .= '<td>' . $linha['Tseg']. '</td>';
$html .= '<td>' . $linha['Tter']. '</td>';
$html .= '<td>' . $linha['Tqua']. '</td>';
$html .= '<td>' . $linha['Tqui']. '</td>';
$html .= '<td>' . $linha['Tsex']. '</td>';
$html .= '<td>' . $linha['Tsab']. '</td>';
$html .= '<td>' . $linha['Nseg']. '</td>';
$html .= '<td>' . $linha['Nter']. '</td>';
$html .= '<td>' . $linha['Nqua']. '</td>';
$html .= '<td>' . $linha['Nqui']. '</td>';
$html .= '<td>' . $linha['Nsex']. '</td>';
$html .= '<td>' . $linha['Nsab']. '</td>';
$html .= '<td>' . $linha['Seg10']. '</td>';
$html .= '<td>' . $linha['Seg11']. '</td>';
$html .= '<td>' . $linha['Seg12']. '</td>';
$html .= '<td>' . $linha['Seg13']. '</td>';
$html .= '<td>' . $linha['Seg14']. '</td>';
$html .= '<td>' . $linha['Seg15']. '</td>';
$html .= '<td>' . $linha['Seg16']. '</td>';
$html .= '<td>' . $linha['Seg17']. '</td>';
$html .= '<td>' . $linha['Seg18']. '</td>';
$html .= '<td>' . $linha['Seg19']. '</td>';
$html .= '<td>' . $linha['Seg20']. '</td>';
$html .= '<td>' . $linha['Seg21']. '</td>';
$html .= '<td>' . $linha['Seg22']. '</td>';
$html .= '<td>' . $linha['Ter10']. '</td>';
$html .= '<td>' . $linha['Ter11']. '</td>';
$html .= '<td>' . $linha['Ter12']. '</td>';
$html .= '<td>' . $linha['Ter13']. '</td>';
$html .= '<td>' . $linha['Ter14']. '</td>';
$html .= '<td>' . $linha['Ter15']. '</td>';
$html .= '<td>' . $linha['Ter16']. '</td>';
$html .= '<td>' . $linha['Ter17']. '</td>';
$html .= '<td>' . $linha['Ter18']. '</td>';
$html .= '<td>' . $linha['Ter19']. '</td>';
$html .= '<td>' . $linha['Ter20']. '</td>';
$html .= '<td>' . $linha['Ter21']. '</td>';
$html .= '<td>' . $linha['Ter22']. '</td>';
$html .= '<td>' . $linha['Quar10']. '</td>';
$html .= '<td>' . $linha['Quar11']. '</td>';
$html .= '<td>' . $linha['Quar12']. '</td>';
$html .= '<td>' . $linha['Quar13']. '</td>';
$html .= '<td>' . $linha['Quar14']. '</td>';
$html .= '<td>' . $linha['Quar15']. '</td>';
$html .= '<td>' . $linha['Quar16']. '</td>';
$html .= '<td>' . $linha['Quar17']. '</td>';
$html .= '<td>' . $linha['Quar18']. '</td>';
$html .= '<td>' . $linha['Quar19']. '</td>';
$html .= '<td>' . $linha['Quar20']. '</td>';
$html .= '<td>' . $linha['Quar21']. '</td>';
$html .= '<td>' . $linha['Quar22']. '</td>';
$html .= '<td>' . $linha['Quin10']. '</td>';
$html .= '<td>' . $linha['Quin11']. '</td>';
$html .= '<td>' . $linha['Quin12']. '</td>';
$html .= '<td>' . $linha['Quin13']. '</td>';
$html .= '<td>' . $linha['Quin14']. '</td>';
$html .= '<td>' . $linha['Quin15']. '</td>';
$html .= '<td>' . $linha['Quin16']. '</td>';
$html .= '<td>' . $linha['Quin17']. '</td>';
$html .= '<td>' . $linha['Quin18']. '</td>';
$html .= '<td>' . $linha['Quin19']. '</td>';
$html .= '<td>' . $linha['Quin20']. '</td>';
$html .= '<td>' . $linha['Quin21']. '</td>';
$html .= '<td>' . $linha['Quin22']. '</td>';
$html .= '<td>' . $linha['Sex10']. '</td>';
$html .= '<td>' . $linha['Sex11']. '</td>';
$html .= '<td>' . $linha['Sex12']. '</td>';
$html .= '<td>' . $linha['Sex13']. '</td>';
$html .= '<td>' . $linha['Sex14']. '</td>';
$html .= '<td>' . $linha['Sex15']. '</td>';
$html .= '<td>' . $linha['Sex16']. '</td>';
$html .= '<td>' . $linha['Sex17']. '</td>';
$html .= '<td>' . $linha['Sex18']. '</td>';
$html .= '<td>' . $linha['Sex19']. '</td>';
$html .= '<td>' . $linha['Sex20']. '</td>';
$html .= '<td>' . $linha['Sex21']. '</td>';
$html .= '<td>' . $linha['Sex22']. '</td>';
$html .= '<td>' . $linha['Sab10']. '</td>';
$html .= '<td>' . $linha['Sab11']. '</td>';
$html .= '<td>' . $linha['Sab12']. '</td>';
$html .= '<td>' . $linha['Sab13']. '</td>';
$html .= '<td>' . $linha['Sab14']. '</td>';
$html .= '<td>' . $linha['Sab15']. '</td>';
$html .= '<td>' . $linha['Sab16']. '</td>';
$html .= '<td>' . $linha['Sab17']. '</td>';
$html .= '<td>' . $linha['Sab18']. '</td>';
$html .= '<td>' . $linha['Sab19']. '</td>';
$html .= '<td>' . $linha['Sab20']. '</td>';
$html .= '<td>' . $linha['Sab21']. '</td>';
$html .= '<td>' . $linha['Sab22']. '</td>';
$html .= '<td>' . $linha['Obs_Geral']. '</td>';
$html .= '<td>' . $linha['AmbienteDescricao']. '</td>';
$html .= '<td>' . $linha['Quadro_Energia']. '</td>';
$html .= '<td>' . $linha['Tomada110v']. '</td>';
$html .= '<td>' . $linha['Tomada220v']. '</td>';
$html .= '<td>' . $linha['Tomada200v']. '</td>';
$html .= '<td>' . $linha['Tipo_Iluminacao']. '</td>';
$html .= '<td>' . $linha['Quantidade_Luminarias']. '</td>';
$html .= '<td>' . $linha['Pe_Direito']. '</td>';
$html .= '<td>' . $linha['Tipo_Revestimento']. '</td>';
$html .= '<td>' . $linha['Quantidade_Portas']. '</td>';
$html .= '<td>' . $linha['Medida_PortaLargura']. '</td>';
$html .= '<td>' . $linha['Medida_PortaAltura']. '</td>';
$html .= '<td>' . $linha['Equipamento_Seguranca']. '</td>';
$html .= '<td>' . $linha['Exaustor']. '</td>';

$sqlcurso="select * from tbl_espaco_curso inner join tbl_curso on tbl_espaco_curso.FK_curso=tbl_curso.PK_CodCurso where FK_espaco=".$linha['PK_CodLaboratorio'];
$qrycurso=mysql_query($sqlcurso);
while($linhacurso=mysql_fetch_array($qrycurso)){
$html .= '<td>' . $linhacurso['Nome_Curso']. '</td>';
}
$html .= '</tr>';
}
$html .= '</table>';

// Configurações header para forçar o download
header ("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header ("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");
header ("Cache-Control: no-cache, must-revalidate");
header ("Pragma: no-cache");
header ("Content-type: application/x-msexcel");
header ("Content-Disposition: attachment; filename=\"{$arquivo}\"" );
header ("Content-Description: PHP Generated Data" );

// Envia o conteúdo do arquivo
echo $html;
?>